name: "Continuous Integration"
on:
  - pull_request
  - push

jobs:
  run:
    name: "Test"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.0', '8.1', '8.2', '8.3']
        composer-version: ['composer:v2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: ${{ matrix.composer-version }}
          extensions: mbstring, xdebug

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Analyse
        run: composer run analyse

      - name: Test
        run: composer run test-ci

      - name: Lint
        run: composer run lint-ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
